// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ3FFq1qiRvNC5U7eGWpuHXvfNCBvbk_c',
    appId: '1:572255477443:web:acbad4affeffc5cc904c76',
    messagingSenderId: '572255477443',
    projectId: 'weather-app-278f3',
    authDomain: 'weather-app-278f3.firebaseapp.com',
    storageBucket: 'weather-app-278f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDojFDwiBwqSUTr7n7udOmfuUwB0Q97Kn8',
    appId: '1:572255477443:android:429068c606c03c03904c76',
    messagingSenderId: '572255477443',
    projectId: 'weather-app-278f3',
    storageBucket: 'weather-app-278f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR0oSSovAqGA3OZYse6UXqanwJNCJzfcE',
    appId: '1:572255477443:ios:ff97096bc12b3bd6904c76',
    messagingSenderId: '572255477443',
    projectId: 'weather-app-278f3',
    storageBucket: 'weather-app-278f3.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR0oSSovAqGA3OZYse6UXqanwJNCJzfcE',
    appId: '1:572255477443:ios:0597586d493c6ae0904c76',
    messagingSenderId: '572255477443',
    projectId: 'weather-app-278f3',
    storageBucket: 'weather-app-278f3.appspot.com',
    iosBundleId: 'com.example.weatherApp.RunnerTests',
  );
}
